spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: true
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        max_fetch_depth: 3
        jdbc:
          batch_size: 10
          fetch_size: 50
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /core